name: vmapplet
channels:
  - fredboudon
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterlab_widgets
  - matplotlib
  - scipy
  - boost
  - boost-cpp
  - cppyy
  - cmake
  - cxx-compiler
  - openalea.plantgl
  - openalea.lpy
  - openalea.mtg
  - pyqglviewer
  - node
  - xlrd
  - flake8
  - pip:
    - pgljupyter>=1.2.*
