name: vmapplet
channels:
  - fredboudon
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - toml
  - matplotlib
  - scipy
  - boost
  - boost-cpp
  - cppyy
  - cmake
  - cxx-compiler
  - openalea.lpy>=3.9.2
  - openalea.mtg
  - xlrd
  - flake8
  - pip
  - pip:
    - pgljupyter==2.0.0
    - -e ..
