name: vmapplet
channels:
  - fredboudon
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab=4.0
  - jupyterlab_widgets=3.0
  - ipywidgets=8.0
  - toml
  - matplotlib
  - scipy
  - boost
  - boost-cpp
  - cppyy=2.4
  - openalea.lpy
  - openalea.plantgl=3.20.1
  - openalea.mtg
  - xlrd
  - pip
  - numpy>=1.22
  - flake8
  - mypy
  - black
  - pytest
  - pip:
    - pgljupyter==2.0.0
    - -e ..
