name: Test

on:
  push:
    branches:
      - master
      - main

jobs:

  test:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: mamba-org/setup-micromamba@v1.4.3
        with:
          environment-file: binder/environment.yml
          init-shell: bash powershell
      - name: Test with pytest
        run: |
          pytest --disable-pytest-warnings